Correct plugin dependency package in README
playframework/twirl pull request #476
Opened 2022-01-17 09:42 UTC by oscarrobinson

The README currently does not have the correct package name for `sbt-twirl`. This PR fixes it.

2022-01-17 09:42 UTC, lightbend-cla-validator commented
Hi @oscarrobinson,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[https://www.lightbend.com/contribute/cla](https://www.lightbend.com/contribute/cla)

2022-01-17 09:42 UTC, lightbend-cla-validator commented
Hi @oscarrobinson,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[https://www.lightbend.com/contribute/cla](https://www.lightbend.com/contribute/cla)

2022-01-29 22:11 UTC, mkurz requested changes

2022-01-29 22:11 UTC, mkurz commented on README.md
> +addSbtPlugin("com.typesafe.sbt" % "sbt-twirl" % "LATEST_VERSION")
@oscarrobinson Thanks! starting with twirl 1.6 we switch to `com.typesafe.play`, I already released 1.6.0-M1 under that groupId.
What do you think about that:

```suggestion
// twirl 1.6 and newer:
addSbtPlugin("com.typesafe.play" % "sbt-twirl" % "LATEST_VERSION")
// twirl 1.5 and before:
addSbtPlugin("com.typesafe.sbt" % "sbt-twirl" % "1.5.1")
```

2022-01-31 16:51 UTC, merged