Fix whitespaces after `else{...}` is not showing
playframework/twirl pull request #712
Opened 2023-11-14 21:19 UTC by yousuketto

The parser does not recognize whitespace after `else {...}` as a plain, so it is not showing.

Refs #711

2023-11-15 10:41 UTC, ihostage approved these changes

2023-11-15 12:21 UTC, mkurz requested changes
LGTM, however I think the last `whitespaceNoBreak?` has to be removed now from
https://github.com/playframework/twirl/blob/6ee921152c206db21d1b8ba7fc7edca8b686ebec/parser/src/main/scala/play/twirl/parser/TwirlParser.scala#L75
or not?

Or actually... isn't following correct actually?
```
  *   elseCall : whitespaceNoBreak? "else" whitespaceNoBreak?  expressionPart
```

2023-11-15 20:21 UTC, yousuketto commented
Oh, I didn't notice the document. As you say, it has to be changed as the following. Thanks.
```
  *   elseCall : whitespaceNoBreak? "else" whitespaceNoBreak? expressionPart
```

2023-11-15 20:39 UTC, yousuketto commented
Furthermore, I noticed that elseIfCall has the same bug as elseCall. I'll fix it too.
```
@(b: Boolean, b2: Boolean)
x@if(b) {ifbody} <-whitespace
x@if(b) {ifbody} else if(b2) {elseifbody} <-whitespace
```
```
scala> com.github.yousuketto.txt.sample(true, false)
val res0: play.twirl.api.TxtFormat.Appendable =
xifbody <-whitespace
xifbody<-whitespace

scala> com.github.yousuketto.txt.sample(false, false)
val res1: play.twirl.api.TxtFormat.Appendable =
x <-whitespace
x<-whitespace

scala> com.github.yousuketto.txt.sample(false, true)
val res2: play.twirl.api.TxtFormat.Appendable =
x <-whitespace
xelseifbody<-whitespace
```

2023-11-15 21:17 UTC, yousuketto commented
I also fixed a bug in elseIfCall. If we need to split this pull request, I'll split it. Please let me know.

2023-11-16 10:18 UTC, mkurz commented
Perfect, thanks!

2023-11-16 10:18 UTC, merged

2023-11-16 10:19 UTC, mkurz commented
@Mergifyio backport main

2023-11-16 11:39 UTC, mkurz commented
Thanks! This is now included in just released twirl 1.6.3 and 2.0.2
- https://github.com/playframework/twirl/releases/tag/1.6.3
- https://github.com/playframework/twirl/releases/tag/2.0.2

2023-11-16 20:01 UTC, yousuketto commented
It's so helpful. Thanks for releasing.